require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "bin/**"
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
RSpec/MultipleExpectations:
  Max: 2
